services:
  neo4j:
    # Neo4j (공식버전으로 빌드 없이 공식 이미지를 그대로 pull 해서 사용)
    # 메이저버전 5 사용
    image: neo4j:5
    environment:
      # .env에 값이 없다면 fail-fast
      NEO4J_AUTH: "${NEO4J_USERNAME:?NEO4J_USERNAME 을 .env 에 설정하세요}/${NEO4J_PASSWORD:?NEO4J_PASSWORD 를 .env 에 설정하세요}"
      NEO4J_initial_dbms_default__database: "${NEO4J_DATABASE:?NEO4J_DATABASE 를 .env 에 설정하세요}"
    ports:
      # port mapping
      - "7474:7474" # HTTP Neo4j Browser (http://localhost:7474)
      - "7687:7687" # Bolt Driver (app.core.db)
    volumes:
      # 아래 선언한 볼륨을 이 컨테이너의 /data 경로에 연결(마운트)하겠다고 선언
      - neo4j_data:/data
    healthcheck:
      test: ["CMD-SHELL", "cypher-shell -u ${NEO4J_USERNAME:?} -p ${NEO4J_PASSWORD:?} 'RETURN 1' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

# 최상위 volumes 선언
# 여기서 선언해야 services 내 명명 volume으로 참조가능
# 위 name이 prefix로 들어간 이름으로 생성됨
volumes:
  neo4j_data:
