services:
  neo4j:
    container_name: finngraph-neo4j
    # 최신 LTS 버전을 위해 버전 명시 X
    image: neo4j
    # port mapping
    ports:
      - "7474:7474"   # HTTP Neo4j Browser (http://localhost:7474)
      - "7687:7687"   # Bolt Driver (app.core.db)
    environment:
      # community version은 username이 neo4j로 고정됨
      NEO4J_AUTH: "${NEO4J_USERNAME}/${NEO4J_PASSWORD}"
      NEO4J_initial_dbms_default__database: "finngraph"
    volumes:
      # Bind Mount 방식으로 진행
      # 로컬 프로젝트에 데이터 마운트
      - ./neo4j_data:/data
      - ./neo4j_logs:/logs
    healthcheck:
      # 시작 전 healthcheck
      test: ["CMD-SHELL", "cypher-shell -u ${NEO4J_USERNAME} -p '${NEO4J_PASSWORD}' 'RETURN 1' || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 30s
